
package teste;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "convertServer", targetNamespace = "http://teste/", wsdlLocation = "http://localhost:8081/hello?wsdl")
public class ConvertServer_Service
    extends Service
{

    private final static URL CONVERTSERVER_WSDL_LOCATION;
    private final static WebServiceException CONVERTSERVER_EXCEPTION;
    private final static QName CONVERTSERVER_QNAME = new QName("http://teste/", "convertServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTSERVER_WSDL_LOCATION = url;
        CONVERTSERVER_EXCEPTION = e;
    }

    public ConvertServer_Service() {
        super(__getWsdlLocation(), CONVERTSERVER_QNAME);
    }

    public ConvertServer_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTSERVER_QNAME, features);
    }

    public ConvertServer_Service(URL wsdlLocation) {
        super(wsdlLocation, CONVERTSERVER_QNAME);
    }

    public ConvertServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTSERVER_QNAME, features);
    }

    public ConvertServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConvertServer
     */
    @WebEndpoint(name = "ConvertServerPort")
    public ConvertServer getConvertServerPort() {
        return super.getPort(new QName("http://teste/", "ConvertServerPort"), ConvertServer.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertServer
     */
    @WebEndpoint(name = "ConvertServerPort")
    public ConvertServer getConvertServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://teste/", "ConvertServerPort"), ConvertServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTSERVER_EXCEPTION!= null) {
            throw CONVERTSERVER_EXCEPTION;
        }
        return CONVERTSERVER_WSDL_LOCATION;
    }

}
